### ISSUE TITLE
bug: Test case erroneously run when more than one tag in inventory 

### ISSUE THREAD

**Issue by kosichd** [aristanetworks/anta#974]
When using tags with the anta.tests.interfaces/VerifyInterfacesStatus test, there seems to be an issue where tests are being executed that should not be. 

This seems to happen when a switch has more than one tag in the inventory file.

 In the below example catalog and inventory files, "management_switch" has two tags, 'osw' and 'DUB'

When running the NRFU command with --tags osw, it should only execute InterfaceStatus against interfaces E51 and E52. However, it seems to be running it against E53/E54 also, which is actually part of the 'DUB' tag, not 'osw'

This causes the test case to fail - 

![ANTA_RUN](https://github.com/user-attachments/assets/ad682697-1cb5-4b04-89c3-b2d7c67c4441)

Steps to recreate:
1) Use the below to create inventory and catalog files
2) From the CLI, run:

```
anta nrfu --username USERNAME--password PASSWORD --inventory recreate_inventory.yml  --catalog recreate_catalog.yml  --tags osw
```

## inventory file 

```
anta_inventory:  
  hosts:
  - host: x.x.x.x
    name: "switch1"
    tags: ['DUB']
  - host :  x.x.x.x
    name: "management_switch"
    tags: ['osw', 'DUB']
```

## catalog file

```
anta.tests.interfaces:
- VerifyInterfacesStatus:
   filters:
     tags: ['DUB', 'GRN']
   interfaces:
     - name: Ethernet51
       status: up
     - name: Ethernet52
       status: up
     - name: Ethernet53
       status: up
     - name: Ethernet54
       status: up
- VerifyInterfacesStatus:
   filters:
     tags: ['osw']
   interfaces:
     - name: Ethernet51
       status: up
     - name: Ethernet52
       status: up
```

**Comment by gmuloc** [comment]
Hello @kosichd this should have be fixed in main in https://github.com/aristanetworks/anta/pull/903 
Could you please it run from main and let us know if this fixes your issue?

We hope to release v1.2.0 soonish

**Comment by kosichd** [comment]
@gmuloc I tried this with the updated code in #903 for runner.py, but still seeing the same behavior

**Comment by kosichd** [comment]
@gmuloc i also tried with cloning the repo to a new directory to get the most recent v1.1.0 updates, and issue still appears to be there.

**Comment by gmuloc** [comment]
Hi @kosichd - so v1.1.0 was released #903 and does indeed have the bug

```
╭────────────────────── Settings ──────────────────────╮
│ - ANTA Inventory contains 2 devices (AsyncEOSDevice) │
│ - Tests catalog contains 2 tests                     │
╰──────────────────────────────────────────────────────╯

[22:40:35] INFO     Preparing ANTA NRFU Run ...                                               tools.py:294
           INFO     Connecting to devices ...                                                 tools.py:294
[22:40:36] INFO     Connecting to devices completed in: 0:00:00.816.                          tools.py:302
           INFO     Preparing the tests ...                                                   tools.py:294
           INFO     Preparing the tests completed in: 0:00:00.004.                            tools.py:302
           INFO     --- ANTA NRFU Run Information ---                                        runner.py:270
                    Number of devices: 2 (1 established)
                    Total number of selected tests: 2
                    Maximum number of open file descriptors for the current ANTA process:
                    16384
                    ---------------------------------
           INFO     Preparing ANTA NRFU Run completed in: 0:00:00.835.                        tools.py:302
           INFO     Running ANTA tests ...                                                    tools.py:294
           INFO     Running ANTA tests completed in: 0:00:00.177.                             tools.py:302
           INFO     Cache statistics for 'management_switch': 1 hits / 2 command(s) (50.00%)  runner.py:75
  • Running NRFU Tests...100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 • 0:00:00 • 0:00:00

                                            All tests results
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃                   ┃                 ┃             ┃                  ┃ Test            ┃               ┃
┃ Device            ┃ Test Name       ┃ Test Status ┃ Message(s)       ┃ description     ┃ Test category ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ management_switch │ VerifyInterfac… │ failure     │ The following    │ Verifies the    │ Interfaces    │
│                   │                 │             │ interface(s) are │ status of the   │               │
│                   │                 │             │ not configured:  │ provided        │               │
│                   │                 │             │ ['Ethernet51',   │ interfaces.     │               │
│                   │                 │             │ 'Ethernet52']    │                 │               │
├───────────────────┼─────────────────┼─────────────┼──────────────────┼─────────────────┼───────────────┤
│ management_switch │ VerifyInterfac… │ failure     │ The following    │ Verifies the    │ Interfaces    │
│                   │                 │             │ interface(s) are │ status of the   │               │
│                   │                 │             │ not configured:  │ provided        │               │
│                   │                 │             │ ['Ethernet51',   │ interfaces.     │               │
│                   │                 │             │ 'Ethernet52',    │                 │               │
│                   │                 │             │ 'Ethernet53',    │                 │               │
│                   │                 │             │ 'Ethernet54']    │                 │               │
└───────────────────┴─────────────────┴─────────────┴──────────────────┴─────────────────┴───────────────┘

**Comment by kosichd** [comment]
Hi @mtache 
I was testing wrong previously.  I was not pulling down main correctly, and was still running v1.1.0. Now installing from main (https://github.com/arista-netdevops-community/anta.git@main), **anta --version** confirms I am running v1.2.0, and the tag behavior looks fixed as you said. 

One last question - When I run the NRFU command without any tags, it tries to run all tests against all switches in the inventory. So in that case, its running/failing a test for E53/E54 against for the management switch with the 'osw' tag. I think that is expected. Can you confirm?

**Comment by mtache** [comment]
Hi @kosichd,

Thanks for confirming. ANTA 1.2.0 has been released 2 days ago so you can upgrade normally and not use the main branch.
The documentation (https://anta.arista.com/stable/cli/tag-management/) should be accurate now.

As per your question, yes that's expected. The management switch has the 'DUB' tag like the test defined for E53/E54 interfaces. So it's most likely a tag assignment issue.

Do not hesitate to open another issue if your use case cannot be implemented with the current tag behaviour.

Closing this issue as this was related to a known bug that has been fixed.
